### ISSUE TITLE
New release to STM32F1xxHAL

### ISSUE THREAD

**Issue by thomaswatts-teamconsulting** [STMicroelectronics/stm32f1xx_hal_driver#10]
The last release / tag (v1.1.9) of STM32F1xxHAL library was in April last year, with several changes made since that time.
When is ST planning to produce a new tag?
My rationale for needing tagged versions is to aid traceability with regards to technical file review in regulated industry.

**Comment by RJMSTM** [comment]
Hello @thomaswatts-teamconsulting,

Thank you for your interest. In response to your question, we are currently planning to release version 1.8.6 in Q4 2024. 

However, at this time, we are unable to provide a specific release date. Thank you for your patience and understanding.

Please allow me thus to close this issue. Thank you for your comprehension.

With Regards,
