### ISSUE TITLE
Missing return at end of a non void function

### ISSUE THREAD

**Issue by RetoFx** [STMicroelectronics/stm32f1xx_hal_driver#12]
Hi
In File stm32f1xx_hal_nand.c at the end of the following functions
HAL_StatusTypeDef HAL_NAND_RegisterCallback()
and
HAL_StatusTypeDef HAL_NAND_UnRegisterCallback()
is no
return status;
Please fix this

**Comment by ASEHSTM** [comment]
ST Internal Reference: 149810

**Comment by ASEHSTM** [comment]
See also [STM32CubeF2#12](https://github.com/STMicroelectronics/STM32CubeF2/issues/12)

**Comment by KRASTM** [comment]
Fixed in https://github.com/STMicroelectronics/stm32f1xx_hal_driver/commit/57dddab747ca555f9f14649a22ff52c71c5198a8
