### ISSUE TITLE
A bug when use HAL_UARTEx_ReceiveToIdle_DMA

### ISSUE THREAD

**Issue by rzzuozuo** [STMicroelectronics/stm32f1xx_hal_driver#4]
**Describe the bug**
Cannot distinguish between half complete in DMA and idle interrupts

**How To Reproduce**
1. set a rxSize

2. use HAL_UARTEx_ReceiveToIdle_DMA

3. send half the data （rxSize/2）

4. HAL_UARTEx_RxEventCallback will be called 2 times with the same input parameter(size)

**Comment by KORKAD** [comment]
Hello @rzzuozuo

This is the normal behavior for this UART service:

     Use of HAL_UARTEx_ReceiveToIdle_DMA service, will generate calls to
     user defined HAL_UARTEx_RxEventCallback callback for each occurrence of
     following events :
     - DMA RX Half Transfer event (HT)
     - DMA RX Transfer Complete event (TC)
     - IDLE event on UART Rx line (indicating a pause is UART reception flow)

for more details please refer to the [UART_ReceptionToIdle_CircularDMA](https://github.com/STMicroelectronics/STM32CubeF4/tree/master/Projects/STM32446E-Nucleo/Examples/UART/UART_ReceptionToIdle_CircularDMA) example available on STM32CubeF4 package.

With Regards

**Comment by ASELSTM** [comment]
Hi @rzzuozuo,

Please allow me to close this thread as answered. Thank you for your comprehension and thank you once more for your contribution.

With regards,
